// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8rNg8jqFHgF6qmizH7cgoXlBGPXlb96o',
    appId: '1:544573662585:web:c101627b23384c104cbba8',
    messagingSenderId: '544573662585',
    projectId: 'blaq01',
    authDomain: 'blaq01.firebaseapp.com',
    storageBucket: 'blaq01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjbse7QWAAWJSW1bp7mY0Y_mHDBjk_4U',
    appId: '1:544573662585:android:379ce28bbbdfd4d74cbba8',
    messagingSenderId: '544573662585',
    projectId: 'blaq01',
    storageBucket: 'blaq01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlqmodAkCQCO0jBxn9B_Xrqj1FEuJJGmI',
    appId: '1:544573662585:ios:e0f91991f806566d4cbba8',
    messagingSenderId: '544573662585',
    projectId: 'blaq01',
    storageBucket: 'blaq01.appspot.com',
    iosClientId: '544573662585-1s6tt1uvcfridh5akee97bkut4ijrt0v.apps.googleusercontent.com',
    iosBundleId: 'com.blaqshyd.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlqmodAkCQCO0jBxn9B_Xrqj1FEuJJGmI',
    appId: '1:544573662585:ios:e0f91991f806566d4cbba8',
    messagingSenderId: '544573662585',
    projectId: 'blaq01',
    storageBucket: 'blaq01.appspot.com',
    iosClientId: '544573662585-1s6tt1uvcfridh5akee97bkut4ijrt0v.apps.googleusercontent.com',
    iosBundleId: 'com.blaqshyd.myApp',
  );
}
